version: '3'
services:
  research_service:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      PYTHONPATH: /workspace
    container_name: research_dev
    volumes:
      - ..:/workspace
    command: sleep infinity
    env_file: ./.env

  neo4j:
    image: neo4j:5.19.0-community
    ports:
      - "7474:7474" # Browser/UI on http://localhost:7474
      - "7687:7687" # Bolt on bolt://localhost:7687
    environment:
      - NEO4J_AUTH=${KNOWLEDGE_DB_USER}/${KNOWLEDGE_DB_PASSWORD}
    volumes:
      - ${NEO4J_DATA_DIR:-../data/neo4j}:/data